os: linux
dist: xenial
language: node_js
jobs:
  include:
  - os: linux
    node_js: 12
  - os: osx
    node_js: 12
addons:
  chrome: stable
  firefox: latest
services:
- xvfb
script:
- npm run ci
before_deploy:
- sed -i 's/"private":\ true/"private":\ false/' package.json
- sed -i -E 's/^dist\/?.*$//' .gitignore
deploy:
  provider: npm
  edge: true
  email:
    secure: TQ/8RCe2sI7bwkR2pPQDADIazItkNWK56PyE9jPZjbDs3OIuFCEzycFoRPjfk+6vjWDExUKw5E2x0+/xf0m5aUhe7xjW6pu8DvIMVbeGGWFJgxAWMQ/IZngSITLFnvAu4A+B6K4Xzx5QDsPAve1NXrprrfOcxxylLRheCihH+7TCTMknucBE+dZaE2QjRjtZYGY94nrZzWrgdz9+u45dwzWoVeRwz+RVnaH6/YnFnogKuOSIBEnGxoVx9Pg5m+91wrDtv60PCDAvIGzngGZwsQuWS3DIY/LBgJFj1/m/qtT1Q7WHfkxV2boY8U60GHb741Q3pW8tyHY2VTuLOyuSyKEsAYzA52RP4SYZTgsYZlqkY+VkBqYEIDmpQnYG6uyWOxMpuf+sS5nLmy55Y6TJty5H9PxuzA8W980CtPdR7ZGkqfkF1oFpzILwpE4/EZWcL9YeMa6NBIZX05kfFGAV0euRWhnPKwOgJOs18GpAxo3FkHyhKkyNoQyvTlUOIQ6aiBJ2PoMsJZjmAsktMGiYKrcORR1skChTkZWCyVOe15TKiQknLZx44zUT7CB02W0FHgxfN0qTKV3nqG0/uDpQ/8cOHmshH0WI4jBFi73D7HSgavPpRYUsZ21lnxCyQYPJABbtU/APAUzrQrHV6P3XlCtvF9xRK1Kkj5pTuqcK1vM=
  api_token:
    secure: "fiM/jn6JGYP1jiACW/NZ6KWfwBPynQmx8OehkmKdgJpFbZlljocQE6en33YJ1jAZkcjNE9xN7yvvquhAoaa/1tn3VGfZaEWBNnYfjfxsi1mKsnn4XZF93//yZqQ1TjpK3JGr2U7sduLL6tehJHZFBNhz23uUAX//vRqrUB1EQ8nEh1HGh3hQIZvIUemm4A93O1TvbHw++hxTjLkd1Ied2wDw2EPmMMg6K4sU6DbWtlzf6ZhjBXWkHDQygvj2vP5PeMh7Mkp7f++P435/1LAZHWpClDVb6V8Y2MjpbNUa3t7H5F6uXYzdAxS0SupA5/JO8kHLDinMcRh9VthF0Fez1qIVtTDIMZYLNFvq16VsvfcrkODm28LPVOvmYcFxUDi5HYN/aM3zn6TvOyQ5WpshrkIn9PPhduv2gz9CAxS/xYTy8fORQ4EUiiISIYmnW7bLHr9x/7wuTnBFtmq1e5A2+LiycB9DtcQCYDOR/m4nnr+9YJwETNhq4SR8f5yJjDlHeGkqssOBaWcNWMln+t2FULeJ7e7EZ2Hwenquzk5aLFuffEKcBrXQKxVaFUR/bJJ1kSYqTQt+idzbAAlmcub8QoRoMqrA0FHfVrbTK/NW+pXJySQV5noWxGJjbkmqungbVgdo4AE4VkENGKX1nZu+F2oWpDm/3Mwvgk+C4fUOpOQ="
  on:
    node_js: 12
    condition:
    - $TRAVIS_BRANCH = master
    - $TRAVIS_EVENT_TYPE = push
    - $TRAVIS_COMMIT_MESSAGE =~ ^v[0-9]+(\.[0-9]+)*
    - $TRAVIS_OS_NAME = linux
notifications:
  email:
    recipients:
    - secure: TQ/8RCe2sI7bwkR2pPQDADIazItkNWK56PyE9jPZjbDs3OIuFCEzycFoRPjfk+6vjWDExUKw5E2x0+/xf0m5aUhe7xjW6pu8DvIMVbeGGWFJgxAWMQ/IZngSITLFnvAu4A+B6K4Xzx5QDsPAve1NXrprrfOcxxylLRheCihH+7TCTMknucBE+dZaE2QjRjtZYGY94nrZzWrgdz9+u45dwzWoVeRwz+RVnaH6/YnFnogKuOSIBEnGxoVx9Pg5m+91wrDtv60PCDAvIGzngGZwsQuWS3DIY/LBgJFj1/m/qtT1Q7WHfkxV2boY8U60GHb741Q3pW8tyHY2VTuLOyuSyKEsAYzA52RP4SYZTgsYZlqkY+VkBqYEIDmpQnYG6uyWOxMpuf+sS5nLmy55Y6TJty5H9PxuzA8W980CtPdR7ZGkqfkF1oFpzILwpE4/EZWcL9YeMa6NBIZX05kfFGAV0euRWhnPKwOgJOs18GpAxo3FkHyhKkyNoQyvTlUOIQ6aiBJ2PoMsJZjmAsktMGiYKrcORR1skChTkZWCyVOe15TKiQknLZx44zUT7CB02W0FHgxfN0qTKV3nqG0/uDpQ/8cOHmshH0WI4jBFi73D7HSgavPpRYUsZ21lnxCyQYPJABbtU/APAUzrQrHV6P3XlCtvF9xRK1Kkj5pTuqcK1vM=
    on_success: change
    on_failure: always
