language: node_js
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    node_js: 10
  - os: osx
    node_js: 10
addons:
  chrome: stable
  firefox: latest
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=google-chrome-stable; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
- npm run ci
before_deploy:
- sed -i 's/"private":\ true/"private":\ false/' package.json
- sed -i -E 's/^dist\/?.*$//' .gitignore
deploy:
  provider: npm
  email:
    secure: TQ/8RCe2sI7bwkR2pPQDADIazItkNWK56PyE9jPZjbDs3OIuFCEzycFoRPjfk+6vjWDExUKw5E2x0+/xf0m5aUhe7xjW6pu8DvIMVbeGGWFJgxAWMQ/IZngSITLFnvAu4A+B6K4Xzx5QDsPAve1NXrprrfOcxxylLRheCihH+7TCTMknucBE+dZaE2QjRjtZYGY94nrZzWrgdz9+u45dwzWoVeRwz+RVnaH6/YnFnogKuOSIBEnGxoVx9Pg5m+91wrDtv60PCDAvIGzngGZwsQuWS3DIY/LBgJFj1/m/qtT1Q7WHfkxV2boY8U60GHb741Q3pW8tyHY2VTuLOyuSyKEsAYzA52RP4SYZTgsYZlqkY+VkBqYEIDmpQnYG6uyWOxMpuf+sS5nLmy55Y6TJty5H9PxuzA8W980CtPdR7ZGkqfkF1oFpzILwpE4/EZWcL9YeMa6NBIZX05kfFGAV0euRWhnPKwOgJOs18GpAxo3FkHyhKkyNoQyvTlUOIQ6aiBJ2PoMsJZjmAsktMGiYKrcORR1skChTkZWCyVOe15TKiQknLZx44zUT7CB02W0FHgxfN0qTKV3nqG0/uDpQ/8cOHmshH0WI4jBFi73D7HSgavPpRYUsZ21lnxCyQYPJABbtU/APAUzrQrHV6P3XlCtvF9xRK1Kkj5pTuqcK1vM=
  api_key:
    secure: "1hPkFbNm3KXsOmBWQcCtSE2gugaK3MYVuqpyPFrk95/Xr2cIhk0pGkPDjsj4nTUR4EGjU1GJ57Bwoa10BoejS7ErQB8oNvB4PAbPCUeN063jwpltmDbJorRhrTconT+Bvat/Zz4G8RnCYbfUMUqmnevTe2fmhi2Kqrkc2tfAWNNe5dtZM+uBow0p7/arNJM+I9a+PcWJ4qoMxwvhetjbJvvJiUENL4PY+n35+AuUxZB/8/LlcTSdZNg4A1+IJoJiaw1POx09XtOKBFPo+Kq9K0ndLfk4NMBnWZGF8jmO2GqZvwcSkIZgv4+UjuImtotbKZ/S2gF7cCZIcv3eDHrmwEcHVTFWT31mKGqX6yvHNiBmBFR8YbNlpxsBiDs6irhJtxEjbMksrlgE3ekFr3R3daIA+gJX0pEWb2n+ztihHFKfh/zz22tyO1T8ODaJ+mzppkf4fNss1zcCzw2Ls6pkedODg29Ny8Tb5mqRLnYm9uBi5kjCw08nWElxzcPDbXgfpaBchgJkIpsIUXT9gHnmbuyS3wK7h6SmlAiEW1LPmGwnPO+eqBqLcFtd2sA955uIM+OXZX8AkqANMSNuq3uENeKKbEacVuYTbfSG36pGG/biotu2RuIhOJCEX/e9a6A4g9yOeon0Rsc2eJb37SNB25r+4X3DDkyonFBVsDeS2Wc="
  on:
    branch: master
    node: 10
    condition: $TRAVIS_OS_NAME = linux
  skip_cleanup: true
notifications:
  email:
    recipients:
    - secure: TQ/8RCe2sI7bwkR2pPQDADIazItkNWK56PyE9jPZjbDs3OIuFCEzycFoRPjfk+6vjWDExUKw5E2x0+/xf0m5aUhe7xjW6pu8DvIMVbeGGWFJgxAWMQ/IZngSITLFnvAu4A+B6K4Xzx5QDsPAve1NXrprrfOcxxylLRheCihH+7TCTMknucBE+dZaE2QjRjtZYGY94nrZzWrgdz9+u45dwzWoVeRwz+RVnaH6/YnFnogKuOSIBEnGxoVx9Pg5m+91wrDtv60PCDAvIGzngGZwsQuWS3DIY/LBgJFj1/m/qtT1Q7WHfkxV2boY8U60GHb741Q3pW8tyHY2VTuLOyuSyKEsAYzA52RP4SYZTgsYZlqkY+VkBqYEIDmpQnYG6uyWOxMpuf+sS5nLmy55Y6TJty5H9PxuzA8W980CtPdR7ZGkqfkF1oFpzILwpE4/EZWcL9YeMa6NBIZX05kfFGAV0euRWhnPKwOgJOs18GpAxo3FkHyhKkyNoQyvTlUOIQ6aiBJ2PoMsJZjmAsktMGiYKrcORR1skChTkZWCyVOe15TKiQknLZx44zUT7CB02W0FHgxfN0qTKV3nqG0/uDpQ/8cOHmshH0WI4jBFi73D7HSgavPpRYUsZ21lnxCyQYPJABbtU/APAUzrQrHV6P3XlCtvF9xRK1Kkj5pTuqcK1vM=
    on_success: change
    on_failure: always
